### ISSUE TITLE
Problem compiling GPU version

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d_globe#358]
I am trying to compile the latest devel version (commit 0bbe2ccb6b).
I am using Intel compiler v. 14.0 and cudatoolkit 5.5.22.
I configure with

    ./configure FC=ifort -mcmodel=large -shared-intel -O2 CC=icc MPIFC=mpif90 MPICC=mpicc CFLAGS=-mcmodel=large -shared-intel --with-cuda=cuda5

The make fails with

    ifort -mcmodel=large -shared-intel -O2 -g   -DFORCE_VECTORIZATION -mod ./obj -I./obj -I.  -I. -
    I./setup -c -o obj/get_attenuation.solverstatic.o src/specfem3D/get_attenuation.f90
    src/specfem3D/get_attenuation.f90(35): error #6580: Name in only-list does not exist.      
    [I_SHOULD_READ_THE_DATABASE]
      I_should_read_the_database, NUMBER_OF_SIMULTANEOUS_RUNS
    ------^
    compilation aborted for src/specfem3D/get_attenuation.f90 (code 1)

Any idea?

Thanks,
David

**Comment by luet** [comment]
I confirm that it compiles with Intel 14.0.0.
